"""Canonical football vocabulary shared across pipeline boundaries."""

from __future__ import annotations

FORWARD_POSITIONS: frozenset[str] = frozenset({"CF", "SS", "LWF", "RWF"})

# Editor position ids 0-12. Iteration order is the editor's canonical position
# order and is also the order every familiarity list is rendered in
POSITION_CODES = (
    "GK",
    "CB",
    "LB",
    "RB",
    "DMF",
    "CMF",
    "LMF",
    "RMF",
    "AMF",
    "LWF",
    "RWF",
    "SS",
    "CF",
)

# Derived rather than written out a second time: the editor id *is* the index in
# ``POSITION_CODES``, so the two tables cannot drift apart
POSITION_IDS = {code: str(index) for index, code in enumerate(POSITION_CODES)}

# The editor's own name for "this player has no Playing Style". It is not a
# contract value: an artifact spells that absence as JSON ``null``, and this is
# only how the absence is encoded on the way into the editor database
NO_PLAYING_STYLE = "N/A"

# The editor stores a nationality as this code, not as a name. It is deliberately
# absent from ``COUNTRY_NAMES``: the code means "no country", which the roster
# contract renders as a blank cell rather than as any spelling of the word
NO_COUNTRY = "0"

# Editor country id -> country name, for the ``Country`` and ``Country2`` columns
# of ``Players.csv``. The ids are the editor's own and are not contiguous; the
# gaps are unassigned in PES 2021 and are absent here rather than filled in.
# Names are spelled exactly as the editor spells them, including its own
# irregularities (``Uae``, ``Gyuana``), because a corrected spelling here would
# be a second, disagreeing source of truth for what the database contains
COUNTRY_NAMES = {
    "1": "Afghanistan",
    "2": "Bahrain",
    "3": "Bangladesh",
    "4": "Bhutan",
    "5": "Brunei",
    "6": "Cambodia",
    "7": "China",
    "8": "Hong Kong",
    "9": "India",
    "10": "Indonesia",
    "11": "Iran",
    "12": "Iraq",
    "13": "Japan",
    "14": "Jordan",
    "15": "North Korea",
    "16": "South Korea",
    "17": "Kuwait",
    "18": "Laos",
    "19": "Lebanon",
    "20": "Macao",
    "21": "Malaysia",
    "22": "Maldives",
    "23": "Mongolia",
    "24": "Myanmar",
    "25": "Nepal",
    "26": "Oman",
    "27": "Pakistan",
    "28": "Palestine",
    "29": "Philippines",
    "30": "Qatar",
    "31": "Saudi Arabia",
    "32": "Singapore",
    "33": "Sri Lanka",
    "34": "Syria",
    "36": "Thailand",
    "37": "Uae",
    "38": "Vietnam",
    "39": "Yemen",
    "40": "Kyrgyz Republic",
    "41": "Tajikistan",
    "42": "Turkmenistan",
    "43": "East Timor",
    "44": "Algeria",
    "45": "Angola",
    "46": "Benin",
    "47": "Botswana",
    "48": "Burkina Faso",
    "49": "Burundi",
    "50": "Cameroon",
    "51": "Cape Verde",
    "52": "Central African Rep.",
    "53": "Chad",
    "54": "The Comoros",
    "55": "Congo Dr",
    "56": "Côte d'Ivoire",
    "57": "Djibouti",
    "58": "Egypt",
    "59": "Equatorial Guinea",
    "60": "Eritrea",
    "61": "Ethiopia",
    "62": "Gabon",
    "63": "Republic of the Gambia",
    "64": "Ghana",
    "65": "Guinea",
    "66": "Guinea-Bissau",
    "67": "Kenya",
    "68": "Lesotho",
    "69": "Liberia",
    "70": "Libya",
    "71": "Madagascar",
    "72": "Malawi",
    "73": "Mali",
    "74": "Mauritania",
    "75": "Mauritius",
    "76": "Morocco",
    "77": "Mozambique",
    "78": "Namibia",
    "79": "Niger",
    "80": "Nigeria",
    "81": "Rwanda",
    "82": "Sao Tomé and Principe",
    "83": "Senegal",
    "84": "Seychelles",
    "85": "Sierra Leone",
    "86": "Somalia",
    "87": "South Africa",
    "88": "Sudan",
    "89": "Swaziland",
    "90": "Tanzania",
    "91": "Togo",
    "92": "Tunisia",
    "93": "Uganda",
    "94": "Zambia",
    "95": "Zimbabwe",
    "98": "Congo",
    "100": "Réunion",
    "103": "Anguilla",
    "104": "Antiqua and Barbuda",
    "105": "Aruba",
    "106": "The Bahamas",
    "107": "Barbados",
    "108": "Belize",
    "109": "Bermuda",
    "110": "Canada",
    "111": "Cayman Islands",
    "112": "Costa Rica",
    "113": "Cuba",
    "114": "Dominica",
    "115": "Dominican Republic",
    "116": "El Salvador",
    "117": "Grenada",
    "118": "Guadeloupe",
    "119": "Guatemala",
    "120": "Haiti",
    "121": "Honduras",
    "122": "Jamaica",
    "123": "Martinique",
    "124": "Mexico",
    "125": "Montserrat",
    "126": "Netherlands Antilles",
    "127": "Nicaragua",
    "128": "Panama",
    "129": "Puerto Rico",
    "130": "Saint Kitts and Nevis",
    "131": "Saint Lucia",
    "132": "St Vincent and Grenadines",
    "133": "Trinidad and Tobago",
    "134": "Turks and Caicos Is.",
    "135": "United States",
    "136": "British Virgin Islands",
    "137": "U.S. Virgin Islands",
    "138": "French Guiana",
    "139": "Suriname",
    "140": "Curaçao",
    "144": "Argentina",
    "145": "Bolivia",
    "146": "Brazil",
    "147": "Chile",
    "148": "Colombia",
    "149": "Ecuador",
    "150": "Paraguay",
    "151": "Peru",
    "152": "Uruguay",
    "153": "Venezuela",
    "159": "Gyuana",
    "161": "American Samoa",
    "162": "Australia",
    "163": "Cook Islands",
    "164": "Fiji",
    "165": "New Caledonia",
    "166": "New Zealand",
    "167": "Papua New Guinea",
    "168": "Samoa",
    "169": "Solomon Islands",
    "170": "Tahiti",
    "171": "Tonga",
    "172": "Vanuatu",
    "176": "Guam",
    "184": "Palau",
    "189": "Israel",
    "190": "Turkey",
    "191": "Albania",
    "192": "Andorra",
    "193": "Armenia",
    "194": "Austria",
    "195": "Azerbaijan",
    "196": "Belarus",
    "197": "Belgium",
    "198": "Bosnia and Herzegovina",
    "199": "Bulgaria",
    "200": "Croatia",
    "201": "Cyprus",
    "202": "Czech Republic",
    "203": "Denmark",
    "204": "England",
    "205": "Estonia",
    "206": "Faroe Islands",
    "207": "Finland",
    "208": "France",
    "209": "Georgia",
    "210": "Germany",
    "211": "Greece",
    "212": "Hungary",
    "213": "Iceland",
    "214": "Ireland",
    "215": "Italy",
    "216": "Kazakhstan",
    "217": "Latvia",
    "218": "Liechtenstein",
    "219": "Lithuania",
    "220": "Luxembourg",
    "221": "Macedonia",
    "222": "Malta",
    "223": "Moldova",
    "224": "Netherlands",
    "225": "Northern Ireland",
    "226": "Norway",
    "227": "Poland",
    "228": "Portugal",
    "229": "Romania",
    "230": "Russia",
    "231": "San Marino",
    "232": "Scotland",
    "234": "Slovakia",
    "235": "Slovenia",
    "236": "Spain",
    "237": "Sweden",
    "238": "Switzerland",
    "239": "Ukraine",
    "240": "Uzbekistan",
    "241": "Wales",
    "245": "Gibraltar",
    "250": "Monaco",
    # The editor's own catch-all for a nationality it does not enumerate
    "260": "Others",
    "298": "Taiwan",
    "303": "Serbia",
    "304": "Montenegro",
    "310": "Sint Maarten",
    "311": "Kosovo",
    "312": "South Sudan",
}

# Name -> PES editor ID. ``N/A`` is retained because it is part of the editor
# mapping (581 shipped players carry it), but it is deliberately absent from
# PLAYING_STYLES: generated profiles must select one of the 21 real styles
PLAYING_STYLE_IDS = {
    NO_PLAYING_STYLE: "0",
    "Goal Poacher": "1",
    "Dummy Runner": "2",
    "Fox in the Box": "3",
    "Prolific Winger": "4",
    "Classic No. 10": "5",
    "Hole Player": "6",
    "Box-to-Box": "7",
    "Anchor Man": "8",
    "The Destroyer": "9",
    "Extra Frontman": "10",
    "Offensive Full-back": "11",
    "Defensive Full-back": "12",
    "Target Man": "13",
    "Creative Playmaker": "14",
    "Build Up": "15",
    "Offensive Goalkeeper": "16",
    "Defensive Goalkeeper": "17",
    "Roaming Flank": "18",
    "Cross Specialist": "19",
    "Orchestrator": "20",
    "Full-back Finisher": "21",
}
PLAYING_STYLE_MAP = {style_id: name for name, style_id in PLAYING_STYLE_IDS.items()}
PLAYING_STYLES = tuple(name for name in PLAYING_STYLE_IDS if name != NO_PLAYING_STYLE)

# Strict in-engine trigger compatibility. Position order follows the supplied
# PES 2021 knowledge base rather than being alphabetically normalized
PLAYING_STYLE_POSITIONS = {
    "Goal Poacher": ("CF", "SS"),
    "Dummy Runner": ("CF", "SS", "AMF"),
    "Fox in the Box": ("CF",),
    "Prolific Winger": ("LWF", "RWF"),
    "Classic No. 10": ("SS", "AMF", "CMF"),
    "Hole Player": ("SS", "LMF", "AMF", "CMF", "RMF"),
    "Box-to-Box": ("LMF", "AMF", "CMF", "DMF", "RMF"),
    "Anchor Man": ("DMF",),
    "The Destroyer": ("CMF", "DMF", "CB"),
    "Extra Frontman": ("CB",),
    "Offensive Full-back": ("LB", "RB"),
    "Defensive Full-back": ("LB", "RB"),
    "Target Man": ("CF",),
    "Creative Playmaker": ("LWF", "SS", "RWF", "LMF", "AMF", "RMF"),
    "Build Up": ("CB",),
    "Offensive Goalkeeper": ("GK",),
    "Defensive Goalkeeper": ("GK",),
    "Roaming Flank": ("LWF", "RWF", "LMF", "RMF"),
    "Cross Specialist": ("LWF", "RWF", "LMF", "RMF"),
    "Orchestrator": ("CMF", "DMF"),
    "Full-back Finisher": ("LB", "RB"),
}

# Key insertion order is load-bearing and is the canonical order of both this
# vocabulary and ``COM_STYLE_COLUMNS`` below: ``player_attributes.constants``
# sorts a player's assigned terms by it, and the Markdown report and the
# dossier present them in that order. Reordering these keys silently reorders
# every one of those listings
PLAYER_SKILL_COLUMNS = {
    "Scissors Feint": "ScissorsFeint",
    "Double Touch": "DoubleTouch",
    "Flip Flap": "FlipFlap",
    "Marseille Turn": "MarseilleTurn",
    "Sombrero": "Sombrero",
    "Cross Over Turn": "CrossOverTurn",
    "Cut Behind & Turn": "CutBehindAndTurn",
    "Scotch Move": "ScotchMove",
    "Sole Control": "StepOnSkillcontrol",
    "Heading": "HeadingSpecial",
    "Long Range Curler": "LongRangeDrive",
    "Chip Shot Control": "Chipshotcontrol",
    "Long Range Shooting": "LongRangeShot",
    "Knuckle Shot": "KnuckleShot",
    "Dipping Shot": "DippingShots",
    "Rising Shots": "RisingShots",
    "Acrobatic Finishing": "AcrobaticFinishing",
    "Heel Trick": "HeelTrick",
    "First-Time Shot": "FirstTimeShot",
    "One-touch Pass": "OneTouchPass",
    "Through Passing": "ThroughPassing",
    "Weighted Pass": "WeightedPass",
    "Pinpoint Crossing": "PinpointCrossing",
    "Outside Curler": "OutsideCurler",
    "Rabona": "Rabona",
    "No Look Pass": "NoLookPass",
    "Low Lofted Pass": "LowLoftedPass",
    "GK Low Punt": "GKLowPunt",
    "GK High Punt": "GKHighPunt",
    "Long Throw": "LongThrow",
    "GK Long Throw": "GKLongThrow",
    "Penalty Specialist": "PenaltySpecialist",
    "GK Penalty Saver": "GKPenaltySaver",
    "Gamesmanship": "Gamesmanship",
    "Man Marking": "ManMarking",
    "Track Back": "TrackBack",
    "Interception": "Interception",
    "Acrobatic Clear": "AcrobaticClear",
    "Captaincy": "Captaincy",
    "Super-sub": "SuperSub",
    "Fighting Spirit": "FightingSpirit",
}
PLAYER_SKILLS = tuple(PLAYER_SKILL_COLUMNS)

COM_STYLE_COLUMNS = {
    "Trickster": "Trickster",
    "Mazing Run": "MazingRun",
    "Speeding Bullet": "SpeedingBullet",
    "Incisive Run": "IncisiveRun",
    "Long Ball Expert": "LongBallExpert",
    "Early Cross": "EarlyCross",
    "Long Ranger": "LongRanger",
}
COM_PLAYING_STYLES = tuple(COM_STYLE_COLUMNS)

# Declaration order is load-bearing: ``player_attributes.constants`` slices the
# first 20 entries as the outfield abilities, 20:25 as the goalkeeping block and
# 25: as the traits block. Reordering silently re-partitions those
ABILITY_COLUMN_MAP = {
    "Offensive Awareness": "OffensiveAwareness",
    "Ball Control": "BallControl",
    "Dribbling": "Dribbling",
    "Tight Possession": "TightPossession",
    "Low Pass": "LowPass",
    "Lofted Pass": "LoftedPass",
    "Finishing": "Finishing",
    "Header": "Heading",
    "Set Piece Taking": "PlaceKicking",
    "Curl": "Curl",
    "Speed": "Speed",
    "Acceleration": "Acceleration",
    "Kicking Power": "KickingPower",
    "Jump": "Jump",
    "Physical Contact": "PhysicalContact",
    "Balance": "Balance",
    "Stamina": "Stamina",
    "Defensive Awareness": "DefensiveAwareness",
    "Ball Winning": "BallWinning",
    "Aggression": "Aggression",
    "GK Awareness": "GKAwareness",
    "GK Catching": "GKCatching",
    "GK Parrying": "GKClearing",
    "GK Reflexes": "GKReflexes",
    "GK Reach": "GKReach",
    "Weak Foot Usage": "WeakFootUsage",
    "Weak Foot Accuracy": "WeakFootAcc",
    "Conditioning": "Form",
    "Injury Resistance": "InjuryResistance",
}
STAT_NAMES = tuple(ABILITY_COLUMN_MAP)

TEAM_KINDS = ("Club", "National")


__all__ = [
    "ABILITY_COLUMN_MAP",
    "COM_PLAYING_STYLES",
    "COM_STYLE_COLUMNS",
    "COUNTRY_NAMES",
    "FORWARD_POSITIONS",
    "NO_COUNTRY",
    "NO_PLAYING_STYLE",
    "PLAYER_SKILLS",
    "PLAYER_SKILL_COLUMNS",
    "PLAYING_STYLES",
    "PLAYING_STYLE_IDS",
    "PLAYING_STYLE_MAP",
    "PLAYING_STYLE_POSITIONS",
    "POSITION_CODES",
    "POSITION_IDS",
    "STAT_NAMES",
    "TEAM_KINDS",
]
